sudo: required

language: node_js
node_js:
- "6"

services:
- docker

install:
- npm install

script:
- if [ "$TRAVIS_BRANCH" == "master" ]; then docker build -t docker.crewmeister.com:5000/sepa-mailer."$TRAVIS_BRANCH"
  .; docker login -u="$DOCKER_USERNAME" -p="$DOCKER_PASSWORD"
  $DOCKER_REGISTRY; docker push $DOCKER_REGISTRY/sepa-mailer."$TRAVIS_BRANCH";
  fi
- 

after_success:
- if [ "$TRAVIS_BRANCH" == "master" ]; then 
  openssl aes-256-cbc -K $encrypted_83630750896a_key -iv $encrypted_83630750896a_iv -in travis_rsa.enc -out travis_rsa -d;
  eval "$(ssh-agent -s)"; 
  chmod 600 $TRAVIS_BUILD_DIR/travis_rsa;
  ssh-add $TRAVIS_BUILD_DIR/travis_rsa; 
  echo $DEPLOY_SERVER_SSH_HOSTKEY;
  echo "$DEPLOY_SERVER $DEPLOY_SERVER_SSH_HOSTKEY" >> ~/.ssh/known_hosts;
  echo "$DEPLOY_SERVER $DEPLOY_SERVER_SSH_HOSTKEY";
  echo ~/.ssh/known_hosts;
  chmod 600 ~/.ssh/known_hosts;
  ssh deploy@$DEPLOY_SERVER "sudo /usr/bin/docker-zero-downtime-deploy.sh sepa-mailer.cfg"; fi
